### ISSUE TITLE
体验问题

### ISSUE THREAD

**Issue by Mr-than** [ColdRain-Moro/Persecution-App#1]
从分类进入之后，返回会直接返回到广场，影响体验

**Comment by hiyasame** [comment]
彳亍 其实就是我懒 没有全部用Navigation

**Comment by Mr-than** [comment]
如果可以的话还可以再顺便优化一下ui  /doge

**Comment by hiyasame** [comment]
😥没得app抄啊 自己写又贼难看

**Comment by Mr-than** [comment]
任务栏字体改成黑色，分类界面放置文字的view圆角的黑边去掉，搜索界面的搜索框窄一点，圆角得再狠一点，然后就是搜索框把键盘收起来之后光标还在闪

**Comment by Mr-than** [comment]
只是建议 /doge

**Comment by hiyasame** [comment]
✔ 下个版本会改

**Comment by hiyasame** [comment]
新版本 v1.2 采纳了部分建议
